# Generated by Django 6.0.7 on 2026-08-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_fc',
        ),
        migrations.AddField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='Prix ($)'),
            preserve_default=False,
        ),
    ]
