# Generated by Django 6.0.7 on 2026-08-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_price_fc_product_price_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price_fc',
            new_name='total_price_usd',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix ($)'),
        ),
    ]
