# Generated by Django 6.0.7 on 2026-08-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_total_price_fc_order_total_price_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('laptop', 'Laptop'), ('accessoire', 'Accessoire')], max_length=50),
        ),
    ]
